name: CI

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_extended_0.69.2_Linux-64bit.deb
          sudo dpkg -i hugo*.deb
      - run: |
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
          sudo mv jq-linux64 /usr/local/bin/jq
      - run: ./ci.sh
